---
title             : "A meta-analysis of the effects of demand characteristics"
shorttitle        : "Demand characteristics meta-analysis"

author: 
  - name          : "Nicholas A. Coles"
    affiliation   : "1"
    corresponding : yes
    address       : "Cordura Hall, 210 Panama St, Stanford, CA 94305" 
    email         : "ncoles@stanford.edu"
  - name          : "Morgan H. Wyatt"
    affiliation   : "1"
  - name          : "Michael C. Frank"
    affiliation   : "1"

affiliation:
  - id            : "1"
    institution   : "Center for the Study of Language and Information, Stanford University"

authornote: |
  All materials, data, and code are available at <insert OSF link>. 

abstract: |
  TBD
  
keywords          : "demand characteristics, hypothesis awareness, placebo effect, research methods, meta-analysis"
wordcount         : "TBD"

bibliography      : "r-references.bib"

floatsintext      : no
linenumbers       : yes
draft             : no
mask              : no

figurelist        : no
tablelist         : no
footnotelist      : no

classoption       : "man"
output            : papaja::apa6_docx
---

```{r setup, include = FALSE}
library("papaja")
r_refs("r-references.bib")
```

Imagine that one day a mysterious man approaches you and begins telling you about a new method for understanding humans: Colesology. The man tells you that Colesology is an extremely effective method for estimating causal relationships. However, he adds that there's a tiny issue: sometimes the method is thrown off by a *methodological artifact*.

When you ask the Colesologist about this artifact, he explains that it sometimes causes researchers to detect an effect that is not real; other times it causes them to miss an effect that is real. Sometimes it causes estimated relationships to be biased upward; other times it causes the estimates to be biased downward. And, in general, it means that the things researchers observe using this method don't necessarily capture real-world human behavior. At this point, you might become skeptical and ask the Colesologist, "How does this methodological artifact work?" His response: they don't know, because sometimes the artifact seems to matter and sometimes it does not.

In this scenario, you would reasonably question whether Colesology is a valid method of scientific inquiry. But here's the thing: we are not describing Colesology, we are describing experimental psychology.

## Debates about demand characteristics as a methodological artifact

In 1962, Martin Orne published a seminal paper highlighting a view that challenged deeply-ingrained beliefs about the role of experiments in psychology. Rather than conceptualizing research participants as passive responders to the experimental context, Orne argued that participants actively navigate and try to make sense of the study context based on their assumptions, beliefs, and motivations. In particular, Orne emphasized that participants are perceptive to *demand characteristics:* "cues which convey an experimental hypothesis to the subject" (p. 779).

In the 60 years since Orne published his seminal paper, demand characteristics have become a literal textbook methodological concern in human subjects research (Sharpe and Whelton, 2016). But textbook psychology often does not capture the reality of the discipline. In actuality, disagreements about the extent to which demand characteristics impact participants' response persist; Uncertainty about how such effects work remains. For example, Mummolo and Peterson (2021) consistently failed to find that manipulations of their communicated hypothesis impacted participants' responses in large replications of classic studies in behavioral economics. Based on these findings, some researchers have argued that the effects of demand characteristics are "rare" (Clayton et al., 2020, p. 1092), supported by "little evidence" (Guess & Coppock, 2020, p. 1512), and/or "limited" (Vial, Brescoll, & Dovidio, 2019, p. 94). Yet, there are some contexts where these effects are more reliable. For example, in three experiments, Coles et al. (2022) found that the effects of posed facial expressions on emotional experience were moderated by demand characteristics. These facial feedback effects were larger when participants were told that the purpose of the study was to demonstrate that the effects are real and smaller when told the purpose was to demonstrate the effects are not real. Nonetheless, Coles et al. were left with the following conclusion: it is still unclear "how and when demand characteristics impact behavior" (p. 61).

In this paper, we provide an overview of a comprehensive framework for conceptualizing the impact of demand characteristics on participants' responses (Rosnow & Rosenthal, 1997). We also review an alternative account that attempts to bridge the gap between research on demand characteristics and research on placebo effects (Coles et al., 2022). Next, we use meta-analysis to conduct the first quantitative synthesis of strict experimental tests of the effects of demand characteristics on participants' responses. Through this meta-analysis, we not only estimate the overall impact of demand characteristics, but also use moderator analyses to provide preliminary tests of predictions made by Rosnow and Rosenthal (1997) and Coles et al., (2022). We end with a discussion of the steps required to transform frameworks about demand characteristics into formal theories---theories we believe might help distinguishing experimental psychology from the invalid methods of Colesology.

## Rosnow and Rosenthal's (1997) demand characteristics framework

Rosnow and Rosenthal (1997) proposed that there are three key moderators of the effects of demand characteristic: (1) receptivity to cues, (2) motivation to provide hypothesis-consistent responses, and (3) opportunity to alter their responses (Figure 1).

### Receptivity to the cues

Participants must be perceptive to demand characteristics in order for them to impact downstream responses (Rosnow and Aiken, 1973; Strohmetz, 2007). As an extreme example, imagine that a researcher hands an infant participant a sheet of paper that precisely explains the researcher's hypothesis. Demand characteristics are certainly present--but they are not predicted to have an impact because the infant is not perceptive to the cues (i.e., cannot read).

### Motivation to provide hypothesis-consistent responses

Early in the history of research on demand characteristics, researchers debated which motivational forces typically underlie response bias (for a review, see Rosnow and Rosenthal, 1997; Weber and Cook, 1972). Orne (1962) originally characterized participants as "good subjects" who change their responses because they are altruistically motivated to help the researcher confirm their hypothesis. Others characterized participants as "apprehensive subjects" who are motivated to respond in a manner that will cause them to be evaluated positively (Riecken, 1962; Rosenberg, 1969, 2009; Sigall, Aronson, and Van Hoose, 1970). Masling (1966) argued that participants sometimes interfere with the purpose of the study ("negativistic subjects"; see also Cook et al. 1970; Silverman, 1977), whereas Fillenbaum (1966) argued that participants attempt to respond as naturally as possible ("faithful subjects"). Although seemingly divided, these early theorists agreed on one overarching principle: that a key driver of the effects of demand characteristics is participants' motivation to provide hypothesis-consistent responses.

Because early demand characteristic theorists often focused on a single predominant subject goal--such as the goal to help the experimenter, be evaluated positively, or respond faithfully--less attention was paid to the notion that participants may have multiple, sometimes competing motivations (Barbuto and Scholl, 1998; Boudreaux & Ozer, 2013). Indeed, when the idea of multiple motivations was explored, it was often done so to highlight the more prominent role of a single goal (e.g., evaluation apprehension vs. motivation to help the experimenter; Sigall, Aronson, and Hoose, 1970). However, Rosnow and Rosenthal (1997) found that people have multiple goals in mind when they conceptualize their role as research participants. Participants describe their role as being similar to situations where one is being altruistic (e.g., giving to charity), being evaluated (e.g., being interviewed for a job), and obeying authority (e.g., obeying a no-smoking sign). All these goals may impact the extent to which participants are motivated to provide hypothesis-consistent responses. Furthermore, these goals can sometimes conflict. For example, imagine that an experimenter is friendly towards the participant--and that the participant is thus motivated to help the experimenter. Now imagine that the participant learns that the experimenter hypothesizes that they will show a race-based preference for job applicants. In this scenario, the motivation to help the experimenter may conflict with the participant's desire to respond in a socially desirable manner. Based on the above observations and reasoning, Rosnow and Rosenthal (1997) suggested that participants can be characterized as being motivated to either (a) non-acquiesce (i.e., not change their responses), (b) acquiesce (i.e., provide hypothesis-consistent responses), or (c) counter-acquiesce (i.e., provide hypothesis-inconsistent responses). Motivation can also be conceptualized on a continuum ranging from highly motivated to acquiesce to highly motivated to non-acquiesce.

### Opportunity to alter responses

No matter how motivated they are to confirm the hypothesis, there is variability in the extent to which participants have the opportunity to alter the outcome-of-interest. Thus, Rosnow and Rosenthal (1997) posited that demand characteristics can impact outcomes that participants can readily alter.

## Coles et al.'s (2022) framework

Coles et al. (2022) argued that demand characteristics not only have the potential to lead to response biases--but also placebo biases (Figure 1). They defined (a) response biases as changes mediated by relatively deliberate changes that participants make to their responses, and (b) placebo effects as changes that are mediated by the relatively automatic activation of beliefs or pre-existing conditioned responses (Zion and Crum, 2018). Thus, unlike Rosnow and Rosenthal (1997), Coles and colleagues argued that demand characteristics can impact responses even when participants have neither the motivation nor opportunity to adjust their responses. Preliminary evidence for this assertion comes from Coles et al.'s observation that participants' beliefs did not always match the demand characteristics manipulation. For example, some participants disclosed that they (a) did not personally believe that posed expressions impacted emotion, but (b) recognized that the experimenter did. Both the manipulation of demand characteristics and measures of participants' beliefs independently moderated facial feedback effects, providing preliminary evidence of distinct psychological mechanisms.

# References

::: {#refs custom-style="Bibliography"}
:::
