---
title: Screening report for "A meta-analysis of the effects of demand characteristics in non-clinical research"
author: "Nicholas A. Coles and Morgan Wyatt"
editor_options: 
  chunk_output_type: console
---
The code was written in `r R.version$version.string` using R Markdown (http://rmarkdown.rstudio.com/).

# Section 1: Data Prep
```{r setup and load packages, include = FALSE}
# clean environment
rm(list = ls())

# load packages
ipak <- function(pkg){
    new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
    
    if (length(new.pkg)) 
        install.packages(new.pkg, dependencies = TRUE)
    
    sapply(pkg, require, character.only = TRUE)
}

# call package function
packages <- c('tidyverse', 'readxl')
ipak(packages)
rm(packages, ipak)

# turn scientific notation off
options(scipen = 999)
```

## Open screening data
```{r}
DF.s <- 
  read_xlsx(path = "metaware_data_raw.xlsx",
            sheet = "records.screening") 
  
  # filter out records we're still waiting on
  #filter(note != "requested from library")
```

## Quality check
```{r}
# MW_include and MW_rationale
DF.s$MW_include %>% unique()

DF.s %>% filter(MW_include == "NA")
DF.s$NC_rationale %>% unique()

# NC_include
DF.s$NC_include %>% unique()
DF.s$NC_rationale %>% unique()

# check to see if there are articles screened as eligible but not coded
## should equal 32 as of 07/27
DF.s %>% 
  filter(NC_include == '1.0') %>%
  nrow()
```

## Identify dissertations
```{r}
DF.s <- DF.s %>% 
  mutate(dissertation = if_else(grepl("dissertation", link),
                                1,
                                0)
         )
```

## Summarize
```{r}
# number screened
nrow(DF.s)

# number of dissertations
DF.s %>% filter(dissertation == 1) %>% nrow()

# number of records determined eligible
DF.s %>% filter(NC_include == 1) %>% nrow()

# year distribution
hist(DF.s$year,
     breaks = seq(from = 1960, 
                  to = 2022,
                  by = 2))
```
