---
title: Vignette creation for "A meta-analysis of the effects of demand characteristics in non-clinical research"
author: "Nicholas A. Coles and Morgan Wyatt"
editor_options: 
  chunk_output_type: console
---
The code was written in `r R.version$version.string` using R Markdown (http://rmarkdown.rstudio.com/).

# Prep environment
```{r setup and load packages, include = FALSE}
# clean environment
rm(list = ls())

# load packages
ipak <- function(pkg){
    new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
    
    if (length(new.pkg)) 
        install.packages(new.pkg, dependencies = TRUE)
    
    sapply(pkg, require, character.only = TRUE)
}

# call package function
packages <- c('tidyverse')
ipak(packages)
rm(packages, ipak)

```

# Prepare vignettes
Get list of files
```{r}

es.DF <- read.csv("es.csv") %>% 
  select(vig.1, vig.2)
es <- c(es.DF$vig.1, es.DF$vig.2) %>% unique()
es = es[es != "N/A"]

vig.DF <- read.csv("vig.csv")
vig <- c(vig.DF$name)

DF <- data.frame(es = es, vig = vig)
```
